######################################################################################################################
#  Copyright 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.                                           #
#                                                                                                                    #
#  Licensed under the Apache License, Version 2.0 (the "License"). You may not use this file except in compliance    #
#  with the License. A copy of the License is located at                                                             #
#                                                                                                                    #
#      http://www.apache.org/licenses/LICENSE-2.0                                                                    #
#                                                                                                                    #
#  or in the 'license' file accompanying this file. This file is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES #
#  OR CONDITIONS OF ANY KIND, express or implied. See the License for the specific language governing permissions    #
#  and limitations under the License.                                                                                #
######################################################################################################################

AWSTemplateFormatVersion: 2010-09-09

Parameters:
  pName:
    Type: String
  pTransitGatewayId:
    Type: String
  pCustomerGatewayAIpAddress:
    Type: String
  pCustomerGatewayBIpAddress:
    Type: String
  pCustomerGatewayABgpAsn:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /compliant/framework/transit/firewall-vpc/virtual-firewall/a/asn
  pCustomerGatewayBBgpAsn:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /compliant/framework/transit/firewall-vpc/virtual-firewall/b/asn

Resources:
  rCustomerGatewayA:
    Type: AWS::EC2::CustomerGateway
    Properties:
      BgpAsn: !Ref pCustomerGatewayABgpAsn
      IpAddress: !Ref pCustomerGatewayAIpAddress
      Tags:
        - Key: Name
          Value: !Sub ${pName}-a-cgw
      Type: ipsec.1
  rVpnConnectionA:
    Type: AWS::EC2::VPNConnection
    Properties:
      CustomerGatewayId: !Ref rCustomerGatewayA
      TransitGatewayId: !Ref pTransitGatewayId
      Tags:
        - Key: Name
          Value: !Sub ${pName}-a-vpn
      Type: ipsec.1
  rCustomerGatewayB:
    Type: AWS::EC2::CustomerGateway
    Properties:
      BgpAsn: !Ref pCustomerGatewayBBgpAsn
      IpAddress: !Ref pCustomerGatewayBIpAddress
      Tags:
        - Key: Name
          Value: !Sub ${pName}-b-cgw
      Type: ipsec.1
  rVpnConnectionB:
    Type: AWS::EC2::VPNConnection
    Properties:
      CustomerGatewayId: !Ref rCustomerGatewayB
      TransitGatewayId: !Ref pTransitGatewayId
      Tags:
        - Key: Name
          Value: !Sub ${pName}-b-vpn
      Type: ipsec.1

Outputs:
  oFirewallVpnConnectionAId:
    Description: Firewall VPN Connection Id
    Value: !Ref rVpnConnectionA
  oFirewallVpnConnectionBId:
    Description: Firewall VPN Connection Id
    Value: !Ref rVpnConnectionB
