######################################################################################################################
#  Copyright 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.                                           #
#                                                                                                                    #
#  Licensed under the Apache License, Version 2.0 (the "License"). You may not use this file except in compliance    #
#  with the License. A copy of the License is located at                                                             #
#                                                                                                                    #
#      http://www.apache.org/licenses/LICENSE-2.0                                                                    #
#                                                                                                                    #
#  or in the 'license' file accompanying this file. This file is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES #
#  OR CONDITIONS OF ANY KIND, express or implied. See the License for the specific language governing permissions    #
#  and limitations under the License.                                                                                #
######################################################################################################################

AWSTemplateFormatVersion: 2010-09-09

Parameters:
  pSolutionInfoBuiltBy:
    Type: String
    Default: wwps-proserve-us-dod
  pSolutionInfoName:
    Type: String
    Default: compliant-framework-for-federal-and-dod-workloads-in-aws-govcloud-us
  pSolutionInfoVersion:
    Type: String
  pS3Bucket:
    Type: String
  pS3Region:
    Type: String
  pRepo:
    Type: String

  pPrimaryRegion:
    Type: String

  #
  # Logging Input Parameters
  #
  pPrincipalOrgId:
    Type: String
  pLoggingAccountId:
    Type: String
  pConsolidatedLogsS3BucketCmkArn:
    Type: String

Resources:
  #
  # Logging Support
  #
  rLoggingStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        pPrincipalOrgId: !Ref pPrincipalOrgId
        pLoggingAccountId: !Ref pLoggingAccountId
        pConsolidatedLogsS3BucketCmkArn: !Ref pConsolidatedLogsS3BucketCmkArn
        pPrimaryRegion: !Ref pPrimaryRegion
      Tags:
        - Key: solution-info:built-by
          Value: !Ref pSolutionInfoBuiltBy
        - Key: solution-info:name
          Value: !Ref pSolutionInfoName
        - Key: solution-info:version
          Value: !Ref pSolutionInfoVersion
      TemplateURL: !Sub
        - https://${pS3Bucket}.${pS3Region}.amazonaws.com/${pRepo}/${templateName}
        - templateName: templates/management-services-logging-assets.yml
