######################################################################################################################
#  Copyright 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.                                           #
#                                                                                                                    #
#  Licensed under the Apache License, Version 2.0 (the "License"). You may not use this file except in compliance    #
#  with the License. A copy of the License is located at                                                             #
#                                                                                                                    #
#      http://www.apache.org/licenses/LICENSE-2.0                                                                    #
#                                                                                                                    #
#  or in the 'license' file accompanying this file. This file is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES #
#  OR CONDITIONS OF ANY KIND, express or implied. See the License for the specific language governing permissions    #
#  and limitations under the License.                                                                                #
######################################################################################################################

AWSTemplateFormatVersion: 2010-09-09

Parameters:
  pFederationName:
    Type: String
  pSamlEndpoint:
    Type: String
    Default: https://signin.aws.amazon.com/saml

Resources:
  #
  # SAML Provider Custom Resource
  #

  # IAM Roles
  rAdministratorAccessRole:
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W28
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:saml-provider/${pFederationName}
            Action: sts:AssumeRoleWithSAML
            Condition:
              StringEquals:
                SAML:aud: !Ref pSamlEndpoint
      Path: /
      ManagedPolicyArns:
        - !Sub arn:${AWS::Partition}:iam::aws:policy/AdministratorAccess
      RoleName: !Sub ${pFederationName}-AdministratorAccess
      MaxSessionDuration: 21600 # 6 hours in seconds

  rSystemAdministratorRole:
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W28
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:saml-provider/${pFederationName}
            Action: sts:AssumeRoleWithSAML
            Condition:
              StringEquals:
                SAML:aud: !Ref pSamlEndpoint
      Path: /
      ManagedPolicyArns:
        - !Sub arn:${AWS::Partition}:iam::aws:policy/job-function/SystemAdministrator
      RoleName: !Sub ${pFederationName}-SystemAdministrator
      MaxSessionDuration: 21600 # 6 hours in seconds

  rViewOnlyAccessRole:
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W28
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:saml-provider/${pFederationName}
            Action: sts:AssumeRoleWithSAML
            Condition:
              StringEquals:
                SAML:aud: !Ref pSamlEndpoint
      Path: /
      ManagedPolicyArns:
        - !Sub arn:${AWS::Partition}:iam::aws:policy/job-function/ViewOnlyAccess
      RoleName: !Sub ${pFederationName}-ViewOnlyAccess
      MaxSessionDuration: 21600 # 6 hours in seconds
