######################################################################################################################
#  Copyright 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.                                           #
#                                                                                                                    #
#  Licensed under the Apache License, Version 2.0 (the "License"). You may not use this file except in compliance    #
#  with the License. A copy of the License is located at                                                             #
#                                                                                                                    #
#      http://www.apache.org/licenses/LICENSE-2.0                                                                    #
#                                                                                                                    #
#  or in the 'license' file accompanying this file. This file is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES #
#  OR CONDITIONS OF ANY KIND, express or implied. See the License for the specific language governing permissions    #
#  and limitations under the License.                                                                                #
######################################################################################################################

AWSTemplateFormatVersion: 2010-09-09

Parameters:
  pDirectoryRtId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /compliant/framework/transit/transit-gateway/directory-route-table/id

  pEnableExternalAccessVpc:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /compliant/framework/transit/external-access-vpc/enabled

  pInspectionVpcTgwAttachId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /compliant/framework/transit/inspection-vpc/tgw-attach/id

  pManagementServicesVpcTgwAttachId:
    Type: String
  pDirectoryVpcTgwAttachId:
    Type: String
  pExternalAccessVpcTgwAttachId:
    Type: String

Conditions:
  cEnableExternalAccessVpc: !Equals [true, !Ref pEnableExternalAccessVpc]

Resources:
  # Associations
  rDirectoryRtAssociationDirectoryVpc:
    Type: AWS::EC2::TransitGatewayRouteTableAssociation
    Properties:
      TransitGatewayAttachmentId: !Ref pDirectoryVpcTgwAttachId
      TransitGatewayRouteTableId: !Ref pDirectoryRtId
  # Propagations
  rDirectoryRtPropagationManagementServicesVpc:
    Type: AWS::EC2::TransitGatewayRouteTablePropagation
    Properties:
      TransitGatewayAttachmentId: !Ref pManagementServicesVpcTgwAttachId
      TransitGatewayRouteTableId: !Ref pDirectoryRtId
  rDirectoryRtPropagationExternalAccessVpc:
    Condition: cEnableExternalAccessVpc
    Type: AWS::EC2::TransitGatewayRouteTablePropagation
    Properties:
      TransitGatewayAttachmentId: !Ref pExternalAccessVpcTgwAttachId
      TransitGatewayRouteTableId: !Ref pDirectoryRtId
  # Routes (Static)
  rDirectoryRtDefaultRouteInspectionVpc:
    Type: AWS::EC2::TransitGatewayRoute
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      TransitGatewayAttachmentId: !Ref pInspectionVpcTgwAttachId
      TransitGatewayRouteTableId: !Ref pDirectoryRtId
